### ISSUE TITLE
Sanitization for every instance of add_setting

### ISSUE THREAD

**Issue by deviodigital** [tommcfarlin/theme-customizer-example#3]
I'm currently submitting a theme to the WordPress repository, and it gave me the following error

> REQUIRED: Found a Customizer setting that did not have a sanitization callback function. Every call to the add_setting() method needs to have a sanitization callback function passed.

I looked through the `functions.php` file and see that all of the settings that aren't text inputs are missing `'sanitize_callback'  => 'cleanblog_sanitize_input',` in the array.

I don't know if this is still in active development since it hasn't been updated in  year, but I figured I'd post about it in case anyone else using this code runs into a similar issue when submitting to the WordPress repository.

**Comment by tommcfarlin** [comment]
> I don't know if this is still in active development since it hasn't been updated in year, but I figured I'd post about it in case anyone else using this code runs into a similar issue when submitting to the WordPress repository.

It's not been updated mainly because it's been tied to an old article. 

Thanks for the points that you've mentioned. if you opt to issue a pull request, I'd happily merge it, just make sure to upload the changelog, as well; otherwise, I'll leave this here as is for others to review when looking through the issues.
